Issue #13: Dynamic Signers
vapor/jwt-provider pull request #14
Opened 2017-06-07 10:10 UTC by valeriomazzeo

This pull request aims to implement what's described in #13.

**Note:** It will require a minor version update of the `JWTProvider` package.

## Configuration

`JWTProvider` can be configured in **3** different ways:

- Legacy custom signer defined in `jwt.json`. 
  - Supports: `hmac`, `rsa`, `esdca`.
- Remote JSON Web Key Set (`jwks.json`) URL defined in `jwt.json`. 
  - Supports: `rsa`.
- Local JSON Web Key Set `jwks.json`. 
  - Supports: `rsa`.

#### Remote JSON Web Key Set

**jwt.json**
```json
{
  "jwks-url": "http://my-domain.com/well-known/jwks.json"
}
```

#### Legacy Custom Signer

This is backwards compatible with the previous implementation.

- type: `unsigned`, `hmac`, `rsa`, `esdca`
- algorithm:
  - type[`hmac`]: `hs256`, `hs384`, `hs512`
  - type[`rsa`]: `rs256`, `rs384`, `rs512`
  - type[`esdca`]: `es256`, `es384`, `es512`

**jwt.json**
```json
{
  "signer": {
    "type": "rsa",
    "algorithm": "rs256",
    "key": "yourkeyhere"
  }
}
```

#### Local JSON Web Key Set

Define a configuration file named `jwks.json`, which conforms to the JSON Web Key Set specification.

## TODO:

- [ ] Support `x5c` as well as `n` and `e` in `JSONWebKeySignerFactory`
- [ ] Rate Limiting when retrieving a new `jwks.json`
- [ ] Unit test

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/Droplet+JWT.swift
> +        get { return self.signers?["_legacy"] }
Please use a constant (e.g. `jwtLegacySignerKey`)

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/Droplet+JWT.swift
> +private let jwtJWKSURL = "jwt-provider:jwks-url"
`jwtJWKSURLKey`

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +    /// the JWT signers and type of payload
Header doc does not match init signature (signers vs. signer)

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
indentation

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
indentation

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/SignerMap.swift
> +            guard let signer = try? JSONWebKeySignerFactory(jwk: key).makeSigner() else {
can be combined with previous guard statement

2017-06-09 16:22 UTC, siemensikkema commented on Sources/JWTProvider/JSONWebKeySignerFactory.swift
> +//
These file headers are not normally part of vapor source code

2017-06-09 16:24 UTC, valeriomazzeo commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
if you press `CTRL+I` it returns to that...

2017-06-09 16:24 UTC, valeriomazzeo commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
same as above

2017-06-09 16:24 UTC, valeriomazzeo commented on Sources/JWTProvider/JSONWebKeySignerFactory.swift
> +//
Ok, I can remove the headers

2017-06-09 16:27 UTC, siemensikkema commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
I know, it's annoying! I think the consensus is that we sometimes ignore Xcode when it comes to formatting.

2017-06-09 16:30 UTC, valeriomazzeo commented on Sources/JWTProvider/SignerMap.swift
> +            guard let signer = try? JSONWebKeySignerFactory(jwk: key).makeSigner() else {
I personally find it less readable, but as you wish...

2017-06-09 16:33 UTC, valeriomazzeo commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
Can you please show me how you want it indented?

2017-06-09 17:13 UTC, siemensikkema commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
`) {` should be aligned with `public`

2017-06-09 17:40 UTC, valeriomazzeo commented on Sources/JWTProvider/PayloadAuthenticationMiddleware.swift
> +        ) {
it's done already

2017-06-13 13:03 UTC, siemensikkema commented
@LoganWright The breaking change label can be removed now that @valeriomazzeo has addressed it with the deprecation warnings right? Or does deprecation still count as a breaking change?

2017-06-20 15:35 UTC, valeriomazzeo commented
Hi guys, @siemensikkema @LoganWright @tanner0101 

Is there any chance we can get this moving?

2017-07-06 16:53 UTC, tanner0101 requested changes
This looks great. Just a couple of minor issues that need to be addressed before we can merge.

Additionally, we will need some updated documentation about how to use these new features and ideally a bit of information about how to upgrade your deprecated code ( @siemensikkema deprecated code should be fine as long as its a minor version bump).

@valeriomazzeo do you think you could include as a comment here some markdown documenting the new API and some additional notes about how to migrate existing code? I can take the markdown from here and put it up on docs.vapor.codes.

2017-07-06 16:53 UTC, tanner0101 commented on Sources/JWTProvider/Droplet+JWT.swift
> +let jwtLegacySignerKey = "jwtLegacySignerKey"
`jwt-providers:legacy-signer` would be better. the namespace is helpful.

2017-07-06 16:53 UTC, tanner0101 commented on Sources/JWTProvider/JWTProviderError.swift
> +    case noJWKSURL
Adding cases to an enum is a breaking change. We'll have to add a new error type or use one of the existing ones.

2017-07-06 16:53 UTC, tanner0101 commented on Sources/JWTProvider/Provider.swift
> -    public let signer: Signer
Looks like this method and the init under it were removed w/o a deprecation, unless I missed it.

2017-07-06 16:53 UTC, tanner0101 commented on Sources/JWTProvider/SignerMap.swift
> +                else {
formatting

2017-07-06 17:02 UTC, valeriomazzeo commented
@tanner0101 detailed documentation is in the PR, I have already suggested to @LoganWright to publish it in docs.vapor.codes once this is merged.

Do you want to add it to the source code as well? I am not sure where, it would probably be faster if you sort it out the way you like it.

2017-07-06 17:03 UTC, valeriomazzeo commented on Sources/JWTProvider/SignerMap.swift
> +                else {
do you prefer the `else` to be aligned with guard? Xcode keeps moving it ...

2017-07-17 13:26 UTC, dlbuckley commented
@tanner0101 @valeriomazzeo whats the latest on this PR?

2017-07-19 23:56 UTC, tanner0101 approved these changes

2017-07-19 23:57 UTC, tanner0101 commented
Thanks for the hard work done here @valeriomazzeo :). Merging this now and I'm going to test it with some large projects I have, update the docs, then release it!

2017-07-19 23:57 UTC, merged